### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by rossiniroberto52** [rossiniroberto52/sistemadeTransporteEscolar#2]
- [ ] Logo picture in the purchase comfirmation pdf
- [x] increase the data in purchase confirmation pdf
- [ ] increase the frontend quality of the project
- [ ] othe thing (idk i put that)
